# Generated by Django 4.1.2 on 2024-07-06 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(db_column='idCategory', primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Foundation',
            fields=[
                ('id_foundation', models.AutoField(db_column='idFoundation', primary_key=True, serialize=False)),
                ('foundations', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(null=True, upload_to='fundaciones')),
                ('description', models.CharField(max_length=450)),
                ('link', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(db_column='idProduct', primary_key=True, serialize=False)),
                ('products', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(null=True, upload_to='productos')),
                ('description', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('id_category', models.ForeignKey(db_column='idCategory', on_delete=django.db.models.deletion.CASCADE, to='appShop.category')),
            ],
        ),
    ]
