# Generated by Django 4.1.2 on 2024-07-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appShop', '0003_alter_foundation_foundations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundation',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
