# Generated by Django 4.1.2 on 2024-07-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appShop', '0004_alter_foundation_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
