# Generated by Django 4.1.2 on 2024-07-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appShop', '0008_remove_contacto_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
