# Generated by Django 4.1.2 on 2024-07-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appShop', '0009_contacto_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.IntegerField(blank=True, max_length=9, null=True),
        ),
    ]
