# Generated by Django 4.1.2 on 2024-07-11 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appShop', '0010_alter_contacto_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='telefono',
        ),
    ]
