# Generated by Django 4.1.2 on 2024-07-14 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appShop', '0011_remove_contacto_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='avisos',
        ),
    ]
